/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;

import tables.*;

/**
 *
 * @author melih
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    
    static User user = new User();
    public MainPage(User user) {
        
        this.user = user;
        initComponents();
        
        add_fld_values();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TabbedMenu = new javax.swing.JTabbedPane();
        PnlProfile = new javax.swing.JPanel();
        kGradientPanel5 = new keeptoo.KGradientPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        lbl_tMatematik = new javax.swing.JLabel();
        fld_profile_name = new javax.swing.JTextField();
        fld_profile_Surname = new javax.swing.JTextField();
        fld_profile_email = new javax.swing.JTextField();
        fld_profile_school = new javax.swing.JTextField();
        fld_profile_class = new javax.swing.JTextField();
        fld_profile_departmen = new javax.swing.JTextField();
        fld_profile_tqc = new javax.swing.JTextField();
        fld_profile_tMatematik = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        lbl_sMatematik = new javax.swing.JLabel();
        fld_profile_sMatematik = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        lbl_sFizik = new javax.swing.JLabel();
        fld_profile_sFizik = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        lbl_sKimya = new javax.swing.JLabel();
        fld_profile_sKimya = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        lbl_sBiyoloji = new javax.swing.JLabel();
        fld_profile_sBiyoloji = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        goalBar = new javax.swing.JProgressBar();
        PnlStatistics = new javax.swing.JPanel();
        kGradientPanel4 = new keeptoo.KGradientPanel();
        jLabel10 = new javax.swing.JLabel();
        PnlArrangement = new javax.swing.JPanel();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        jLabel8 = new javax.swing.JLabel();
        PnlQA = new javax.swing.JPanel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jLabel18 = new javax.swing.JLabel();
        PnlInfo = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel6 = new javax.swing.JLabel();
        PnlQ = new javax.swing.JPanel();
        kGradientPanel6 = new keeptoo.KGradientPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/information.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 60, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 60, 80));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/data-analysis.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 60, 80));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/trophy.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 60, 80));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/open-book.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 60, 80));

        kGradientPanel5.setkEndColor(new java.awt.Color(0, 0, 204));
        kGradientPanel5.setkGradientFocus(1200);
        kGradientPanel5.setkStartColor(new java.awt.Color(153, 0, 153));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/profile64.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(200, 204, 255));
        jLabel9.setText("Name");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 102));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(200, 204, 255));
        jLabel13.setText("Surname");

        jSeparator2.setForeground(new java.awt.Color(0, 0, 102));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(200, 204, 255));
        jLabel14.setText("Email");

        jSeparator3.setForeground(new java.awt.Color(0, 0, 102));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(200, 204, 255));
        jLabel15.setText("School");

        jSeparator4.setForeground(new java.awt.Color(0, 0, 102));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(200, 204, 255));
        jLabel16.setText("Class");

        jSeparator5.setForeground(new java.awt.Color(0, 0, 102));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(200, 204, 255));
        jLabel17.setText("Department");

        jSeparator6.setForeground(new java.awt.Color(0, 0, 102));

        jSeparator8.setForeground(new java.awt.Color(0, 0, 102));
        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(200, 204, 255));
        jLabel12.setText("Target Question Count");

        jSeparator9.setForeground(new java.awt.Color(0, 0, 102));

        lbl_tMatematik.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_tMatematik.setForeground(new java.awt.Color(200, 204, 255));
        lbl_tMatematik.setText("Temel Matematik");

        fld_profile_name.setEditable(false);
        fld_profile_name.setBackground(new java.awt.Color(153, 0, 153));
        fld_profile_name.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fld_profile_name.setForeground(new java.awt.Color(200, 204, 255));
        fld_profile_name.setText("Temp");
        fld_profile_name.setBorder(null);

        fld_profile_Surname.setEditable(false);
        fld_profile_Surname.setBackground(new java.awt.Color(153, 0, 153));
        fld_profile_Surname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fld_profile_Surname.setForeground(new java.awt.Color(200, 204, 255));
        fld_profile_Surname.setText("Temp");
        fld_profile_Surname.setBorder(null);

        fld_profile_email.setEditable(false);
        fld_profile_email.setBackground(new java.awt.Color(153, 0, 153));
        fld_profile_email.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fld_profile_email.setForeground(new java.awt.Color(200, 204, 255));
        fld_profile_email.setText("temp@gmail.com");
        fld_profile_email.setBorder(null);

        fld_profile_school.setEditable(false);
        fld_profile_school.setBackground(new java.awt.Color(153, 0, 153));
        fld_profile_school.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fld_profile_school.setForeground(new java.awt.Color(200, 204, 255));
        fld_profile_school.setText("Temp High School");
        fld_profile_school.setBorder(null);

        fld_profile_class.setEditable(false);
        fld_profile_class.setBackground(new java.awt.Color(153, 0, 153));
        fld_profile_class.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fld_profile_class.setForeground(new java.awt.Color(200, 204, 255));
        fld_profile_class.setText("12");
        fld_profile_class.setBorder(null);

        fld_profile_departmen.setEditable(false);
        fld_profile_departmen.setBackground(new java.awt.Color(153, 0, 153));
        fld_profile_departmen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fld_profile_departmen.setForeground(new java.awt.Color(200, 204, 255));
        fld_profile_departmen.setText("Sayisal");
        fld_profile_departmen.setBorder(null);

        fld_profile_tqc.setBackground(new java.awt.Color(66, 17, 164));
        fld_profile_tqc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fld_profile_tqc.setForeground(new java.awt.Color(200, 204, 255));
        fld_profile_tqc.setText("120");
        fld_profile_tqc.setBorder(null);

        fld_profile_tMatematik.setBackground(new java.awt.Color(66, 17, 164));
        fld_profile_tMatematik.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fld_profile_tMatematik.setForeground(new java.awt.Color(200, 204, 255));
        fld_profile_tMatematik.setText("20");
        fld_profile_tMatematik.setBorder(null);

        jSeparator10.setForeground(new java.awt.Color(0, 0, 102));

        lbl_sMatematik.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_sMatematik.setForeground(new java.awt.Color(200, 204, 255));
        lbl_sMatematik.setText("Secmeli Matematik");

        fld_profile_sMatematik.setBackground(new java.awt.Color(66, 17, 164));
        fld_profile_sMatematik.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fld_profile_sMatematik.setForeground(new java.awt.Color(200, 204, 255));
        fld_profile_sMatematik.setText("20");
        fld_profile_sMatematik.setBorder(null);

        jSeparator11.setForeground(new java.awt.Color(0, 0, 102));

        lbl_sFizik.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_sFizik.setForeground(new java.awt.Color(200, 204, 255));
        lbl_sFizik.setText("Secmeli Fizik");

        fld_profile_sFizik.setBackground(new java.awt.Color(66, 17, 164));
        fld_profile_sFizik.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fld_profile_sFizik.setForeground(new java.awt.Color(200, 204, 255));
        fld_profile_sFizik.setText("20");
        fld_profile_sFizik.setBorder(null);

        jSeparator12.setForeground(new java.awt.Color(0, 0, 102));

        lbl_sKimya.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_sKimya.setForeground(new java.awt.Color(200, 204, 255));
        lbl_sKimya.setText("Secmeli Kimya");

        fld_profile_sKimya.setBackground(new java.awt.Color(66, 17, 164));
        fld_profile_sKimya.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fld_profile_sKimya.setForeground(new java.awt.Color(200, 204, 255));
        fld_profile_sKimya.setText("20");
        fld_profile_sKimya.setBorder(null);

        jSeparator13.setForeground(new java.awt.Color(0, 0, 102));

        lbl_sBiyoloji.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_sBiyoloji.setForeground(new java.awt.Color(200, 204, 255));
        lbl_sBiyoloji.setText("Secmeli Biyoloji");

        fld_profile_sBiyoloji.setBackground(new java.awt.Color(66, 17, 164));
        fld_profile_sBiyoloji.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fld_profile_sBiyoloji.setForeground(new java.awt.Color(200, 204, 255));
        fld_profile_sBiyoloji.setText("20");
        fld_profile_sBiyoloji.setBorder(null);

        jSeparator14.setForeground(new java.awt.Color(0, 0, 102));

        goalBar.setForeground(new java.awt.Color(102, 102, 102));
        goalBar.setStringPainted(true);

        javax.swing.GroupLayout kGradientPanel5Layout = new javax.swing.GroupLayout(kGradientPanel5);
        kGradientPanel5.setLayout(kGradientPanel5Layout);
        kGradientPanel5Layout.setHorizontalGroup(
            kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel5Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel9)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addComponent(jLabel15)
                    .addComponent(jSeparator4)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fld_profile_name)
                    .addComponent(fld_profile_Surname)
                    .addComponent(fld_profile_email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(fld_profile_school, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(fld_profile_class, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(fld_profile_departmen, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(198, 198, 198)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator9)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(lbl_tMatematik)
                    .addComponent(fld_profile_tqc)
                    .addComponent(fld_profile_tMatematik, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator10)
                    .addComponent(lbl_sMatematik)
                    .addComponent(fld_profile_sMatematik)
                    .addComponent(jSeparator11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_sFizik)
                    .addComponent(fld_profile_sFizik)
                    .addComponent(jSeparator12)
                    .addComponent(lbl_sKimya)
                    .addComponent(fld_profile_sKimya)
                    .addComponent(jSeparator13, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(lbl_sBiyoloji)
                    .addComponent(fld_profile_sBiyoloji)
                    .addComponent(jSeparator14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(kGradientPanel5Layout.createSequentialGroup()
                .addGroup(kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel5Layout.createSequentialGroup()
                        .addGap(405, 405, 405)
                        .addComponent(jLabel11))
                    .addGroup(kGradientPanel5Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(goalBar, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        kGradientPanel5Layout.setVerticalGroup(
            kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel5Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(kGradientPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(11, 11, 11)
                        .addComponent(fld_profile_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addGap(11, 11, 11)
                        .addComponent(fld_profile_Surname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fld_profile_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fld_profile_school, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fld_profile_class, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fld_profile_departmen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(11, 11, 11)
                        .addComponent(fld_profile_tqc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_tMatematik)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fld_profile_tMatematik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_sMatematik)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fld_profile_sMatematik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_sFizik)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fld_profile_sFizik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(lbl_sKimya)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fld_profile_sKimya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_sBiyoloji)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fld_profile_sBiyoloji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator8))
                .addGap(18, 18, 18)
                .addComponent(goalBar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PnlProfileLayout = new javax.swing.GroupLayout(PnlProfile);
        PnlProfile.setLayout(PnlProfileLayout);
        PnlProfileLayout.setHorizontalGroup(
            PnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PnlProfileLayout.setVerticalGroup(
            PnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        TabbedMenu.addTab("tab1", PnlProfile);

        kGradientPanel4.setkEndColor(new java.awt.Color(0, 0, 204));
        kGradientPanel4.setkGradientFocus(1200);
        kGradientPanel4.setkStartColor(new java.awt.Color(153, 0, 153));

        jLabel10.setText("Statistics");

        javax.swing.GroupLayout kGradientPanel4Layout = new javax.swing.GroupLayout(kGradientPanel4);
        kGradientPanel4.setLayout(kGradientPanel4Layout);
        kGradientPanel4Layout.setHorizontalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel4Layout.createSequentialGroup()
                .addGap(414, 414, 414)
                .addComponent(jLabel10)
                .addContainerGap(440, Short.MAX_VALUE))
        );
        kGradientPanel4Layout.setVerticalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel4Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel10)
                .addContainerGap(727, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PnlStatisticsLayout = new javax.swing.GroupLayout(PnlStatistics);
        PnlStatistics.setLayout(PnlStatisticsLayout);
        PnlStatisticsLayout.setHorizontalGroup(
            PnlStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PnlStatisticsLayout.setVerticalGroup(
            PnlStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        TabbedMenu.addTab("tab2", PnlStatistics);

        kGradientPanel3.setkEndColor(new java.awt.Color(0, 0, 204));
        kGradientPanel3.setkGradientFocus(1200);
        kGradientPanel3.setkStartColor(new java.awt.Color(153, 0, 153));

        jLabel8.setText("Arrangement");

        javax.swing.GroupLayout kGradientPanel3Layout = new javax.swing.GroupLayout(kGradientPanel3);
        kGradientPanel3.setLayout(kGradientPanel3Layout);
        kGradientPanel3Layout.setHorizontalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addGap(379, 379, 379)
                .addComponent(jLabel8)
                .addContainerGap(451, Short.MAX_VALUE))
        );
        kGradientPanel3Layout.setVerticalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel8)
                .addContainerGap(721, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PnlArrangementLayout = new javax.swing.GroupLayout(PnlArrangement);
        PnlArrangement.setLayout(PnlArrangementLayout);
        PnlArrangementLayout.setHorizontalGroup(
            PnlArrangementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PnlArrangementLayout.setVerticalGroup(
            PnlArrangementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        TabbedMenu.addTab("tab3", PnlArrangement);

        kGradientPanel2.setkEndColor(new java.awt.Color(0, 0, 204));
        kGradientPanel2.setkGradientFocus(1200);
        kGradientPanel2.setkStartColor(new java.awt.Color(153, 0, 153));

        jLabel18.setText("question Answer");

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(376, 376, 376)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(429, Short.MAX_VALUE))
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel18)
                .addContainerGap(722, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PnlQALayout = new javax.swing.GroupLayout(PnlQA);
        PnlQA.setLayout(PnlQALayout);
        PnlQALayout.setHorizontalGroup(
            PnlQALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PnlQALayout.setVerticalGroup(
            PnlQALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        TabbedMenu.addTab("tab4", PnlQA);

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 0, 204));
        kGradientPanel1.setkGradientFocus(1200);
        kGradientPanel1.setkStartColor(new java.awt.Color(153, 0, 153));

        jLabel6.setText("INFO");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(421, 421, 421)
                .addComponent(jLabel6)
                .addContainerGap(452, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel6)
                .addContainerGap(744, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PnlInfoLayout = new javax.swing.GroupLayout(PnlInfo);
        PnlInfo.setLayout(PnlInfoLayout);
        PnlInfoLayout.setHorizontalGroup(
            PnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PnlInfoLayout.setVerticalGroup(
            PnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        TabbedMenu.addTab("tab5", PnlInfo);

        kGradientPanel6.setkEndColor(new java.awt.Color(0, 0, 204));
        kGradientPanel6.setkGradientFocus(1200);
        kGradientPanel6.setkStartColor(new java.awt.Color(153, 0, 153));

        jLabel19.setText("Qustions");

        javax.swing.GroupLayout kGradientPanel6Layout = new javax.swing.GroupLayout(kGradientPanel6);
        kGradientPanel6.setLayout(kGradientPanel6Layout);
        kGradientPanel6Layout.setHorizontalGroup(
            kGradientPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel6Layout.createSequentialGroup()
                .addGap(379, 379, 379)
                .addComponent(jLabel19)
                .addContainerGap(469, Short.MAX_VALUE))
        );
        kGradientPanel6Layout.setVerticalGroup(
            kGradientPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel6Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel19)
                .addContainerGap(708, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PnlQLayout = new javax.swing.GroupLayout(PnlQ);
        PnlQ.setLayout(PnlQLayout);
        PnlQLayout.setHorizontalGroup(
            PnlQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PnlQLayout.setVerticalGroup(
            PnlQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        TabbedMenu.addTab("tab6", PnlQ);

        jPanel1.add(TabbedMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, -40, 900, 840));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/question.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 60, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        
        
        TabbedMenu.setSelectedIndex(0);
        
        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked

         TabbedMenu.setSelectedIndex(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        TabbedMenu.setSelectedIndex(2);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
         TabbedMenu.setSelectedIndex(5); 
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
         TabbedMenu.setSelectedIndex(4);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        TabbedMenu.setSelectedIndex(3);
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage(user).setVisible(true);
            }
        });
    }
    
    public void add_fld_values(){
        
        fld_profile_name.setText(user.getName());
        fld_profile_Surname.setText(user.getSurName());
        fld_profile_class.setText(user.getClass_());
        fld_profile_departmen.setText(Integer.toString(user.getDepId()));
        fld_profile_email.setText(user.getMail());
        fld_profile_school.setText(user.getSchool());
          
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlArrangement;
    private javax.swing.JPanel PnlInfo;
    private javax.swing.JPanel PnlProfile;
    private javax.swing.JPanel PnlQ;
    private javax.swing.JPanel PnlQA;
    private javax.swing.JPanel PnlStatistics;
    private javax.swing.JTabbedPane TabbedMenu;
    private javax.swing.JTextField fld_profile_Surname;
    private javax.swing.JTextField fld_profile_class;
    private javax.swing.JTextField fld_profile_departmen;
    private javax.swing.JTextField fld_profile_email;
    private javax.swing.JTextField fld_profile_name;
    private javax.swing.JTextField fld_profile_sBiyoloji;
    private javax.swing.JTextField fld_profile_sFizik;
    private javax.swing.JTextField fld_profile_sKimya;
    private javax.swing.JTextField fld_profile_sMatematik;
    private javax.swing.JTextField fld_profile_school;
    private javax.swing.JTextField fld_profile_tMatematik;
    private javax.swing.JTextField fld_profile_tqc;
    private javax.swing.JProgressBar goalBar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private keeptoo.KGradientPanel kGradientPanel3;
    private keeptoo.KGradientPanel kGradientPanel4;
    private keeptoo.KGradientPanel kGradientPanel5;
    private keeptoo.KGradientPanel kGradientPanel6;
    private javax.swing.JLabel lbl_sBiyoloji;
    private javax.swing.JLabel lbl_sFizik;
    private javax.swing.JLabel lbl_sKimya;
    private javax.swing.JLabel lbl_sMatematik;
    private javax.swing.JLabel lbl_tMatematik;
    // End of variables declaration//GEN-END:variables
}
